# Generated by Django 5.2.17 on 2026-10-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='content_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='audit',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='page_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='audit',
            name='response_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audit',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
