# Generated by Django 5.2.17 on 2026-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_audit_completed_at_audit_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='issues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
